# Generated by Django 3.2.14 on 2022-07-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_app', '0002_addproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='price',
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='description',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
