# Generated by Django 3.2.14 on 2022-07-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_app', '0003_auto_20220728_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
