# Generated by Django 3.2.14 on 2022-07-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_app', '0004_alter_addproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
