# Generated by Django 3.2.14 on 2022-07-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_app', '0006_auto_20220728_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='min_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
