# Generated by Django 3.2.14 on 2022-07-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding_app', '0007_addproduct_min_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproduct',
            old_name='min_bid',
            new_name='max_bid',
        ),
    ]
